---
title: "Projeto"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Códigos

```{r c1dasmdlanlkmas}
fifa <- read.csv(file="~/Desktop/data.csv",head=TRUE)
fifa$X <- NULL
fifa$ID <- NULL
fifa$Name <- NULL
fifa$Photo <- NULL
fifa$Flag <- NULL
fifa$Nationality <- NULL
fifa$Club <- NULL
fifa$Flag <- NULL
fifa$Club.Logo <- NULL
fifa$Value <- NULL
fifa$Wage <- NULL
fifa$Special <- NULL
fifa$International.Reputation <- NULL
fifa$Flag <- NULL
fifa$Work.Rate <- NULL
fifa$Body.Type <- NULL
fifa$Real.Face <- NULL
fifa$Position <- NULL
fifa$Jersey.Number <- NULL
fifa$Joined <- NULL
fifa$Loaned.From <- NULL
fifa$Contract.Valid.Until <- NULL
fifa$LS <- NULL
fifa$ST <- NULL
fifa$RS <- NULL
fifa$LW <- NULL
fifa$LF <- NULL
fifa$CF <- NULL
fifa$RF <- NULL
fifa$RW <- NULL
fifa$LAM <- NULL
fifa$CAM <- NULL
fifa$RAM <- NULL
fifa$LM <- NULL
fifa$LCM <- NULL
fifa$CM <- NULL
fifa$RCM <- NULL
fifa$RM <- NULL
fifa$LWB <- NULL
fifa$LDM <- NULL
fifa$CDM <- NULL
fifa$RDM <- NULL
fifa$RWB <- NULL
fifa$LB <- NULL
fifa$LCB <- NULL
fifa$CB <- NULL
fifa$RCB <- NULL
fifa$RB <- NULL
fifa$Release.Clause <- NULL
fifa$Weight <- NULL
fifa$Height <- NULL
tabela <- fifa

head(fifa)
```

## Plots

Plots das estatísticas

```{r asiojdasd}
library(shiny)
library(ggplot2)
ui <- fluidPage(
  titlePanel("Gráfico de Variáveis no Fifa"),
  sidebarLayout(
    sidebarPanel(
      selectInput("co1", "Reac1", colnames(fifa)),
      selectInput("co2", "Reac2", colnames(fifa)),
      checkboxInput("sidebar","Create Side Bar")
  ),
    mainPanel(
      plotOutput("bar")
    )
  )
)

server <- function(input,output){

  output$bar <- renderPlot({
    barplot(fifa)
     
  })
}
shinyApp(ui=ui, server=server)


```